name: Snyk cli SCA

on: 
  workflow_dispatch:

env:
  SNYK_SEVERITY_THRESHOLD_LEVEL: critical

jobs:
  snyk-cli-scan:
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
            node-version: '16'
            
      - name: Set up Snyk
        uses: snyk/actions/setup@master        
      
      - name: Scan nodejs
        run: |        
          snyk test --severity-threshold=critical        
